%% --- Global Data Storage Declaration ---
global SIM_DATA; 

% Initialize struct to store data
SIM_DATA = struct('t', [], 'V', [], 'V_no_sdslip', [], ...
    ... % Velocities in no-sideslip rotated frame
    'u_no_sdslip', [], 'v_no_sdslip', [], 'w_no_sdslip', [], ...
    ... % Aero Forces in Body Frame
    'Fx_aero_b', [], 'Fy_aero_b', [], 'Fz_aero_b', [], ...
    ... % Aero Forces in wind frame and rotated by alpha_equivalent for no-sideslip frame
    'Lift_sdslip', [], 'Drag_sdslip', [], 'Normal_force', [], 'Axial_force', [], ...
    ... % Forces in body frame (complete, including gravity)
    'Fx_b', [], 'Fy_b', [], 'Fz_b', [], ...
    ... % Forces in de-spun frame (complete, including gravity)
    'Fx_nr', [], 'Fy_nr', [], 'Fz_nr', [], ...
    ... % Total Moments in Body Frame
    'Mx_b', [], 'My_b', [], 'Mz_b', [], ...
    ... % Moments computed in the no-sideslip frame (x and z components should be zero)
    'Mx_no_sdslip', [], 'My_no_sdslip', [], 'Mz_no_sdslip', [], ...
     ... % Moments computed in the despun frame 
    'Mx_nr', [], 'My_nr', [], 'Mz_nr', [], ...
    ... % Aero oefficients
    'CL', [], 'CD', [], 'Cm', [], ...
    ... % Angles / derived angles
    'alpha', [], 'beta', [], 'no_sdslip_angle', [], 'alpha_equivalent', [], ...
    ... % Centre of Pressure fraction location
    'CoP_fraction', [] ...
);